apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: nginx
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/bitnami/charts
      ref: f256d281d17db5a595ddc6cdfa06bd1a30cbf70b
      subPath: bitnami/nginx
    path: root
  - git:
      url: https://github.com/bitnami/charts
      ref: f256d281d17db5a595ddc6cdfa06bd1a30cbf70b
      subPath: bitnami/common
    path: root/charts/common
  template:
  - helmTemplate:
      path: root
      valuesFrom:
      - secretRef:
          name: nginx-values
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          remove-lb.yml: |
            #@ load("@ytt:overlay", "overlay")
            #@overlay/match by=overlay.subset({"kind":"Service","metadata":{"name":"nginx"}})
            ---
            spec:
              type: ClusterIP
              #@overlay/remove
              externalTrafficPolicy:
  - kbld: {}
  deploy:
  - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-values
  namespace: default
stringData:
  data.yml: |
    serverBlock: |-
      server {
        listen 0.0.0.0:8080;
        location / {
          return 200 "hello from kapp-controller!";
        }
      }
